### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [SandraSw/TeaCosy#5]
Grade: Meets Expectations

Summary:
Sandra congrats on finishing the Tea Cozy project! You did a fantastic job overall with the formatting of all your code to improve its readability and making sure you didn't have any syntax errors present. Apart from this, you did a nice job applying your CSS efficiently as I didn't see any duplicate styles in your stylesheet. 

To expand your CSS skills consider reading about [hover effects](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover), [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions), and [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). Both the pseudo-class hover and the property transitions are widely used together as seen in this [codepen](https://codepen.io/JacobStone/pen/GfLEn). As for variables they are a great tool you might be able to make use of to not only improve the readability of your file but also increase the maintainability of your stylesheet.

**Comment by SandraSw** [comment]
Thanks Jim for your feedbacks and recommended readings! Will do definitively :)

Sandra
